version: '3'

services:
  db:
    image: postgis/postgis:13-3.0
    environment:
      - POSTGRES_PASSWORD=onadata
      - POSTGRES_USER=onadata
      - POSTGRES_DB=onadata
    volumes:
      # One level above the code to prevent having to move or delete
      # it everytime we rebuild.
      - ../.onadata_db:/var/lib/postgresql/data
  queue:
    image: redis:6-alpine
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: onadata:latest
    volumes:
      # For local development
      - .:/srv/onadata
      - .inputrc:/home/onadata/.inputrc
      - .bash_history:/home/onadata/.bash_history
    ports:
      - "8000:8000"
    depends_on:
      - db
      - queue
    environment:
      - SELECTED_PYTHON=python3.9
      - INITDB=false
  notifications:
    image: emqx/emqx:4.3.2
    ports:
      - "1883:1883"
      - "8080:8080"
    volumes:
      - ../.onadata_mqtt/data:/opt/emqx/data
      - ../.onadata_mqtt/etc:/opt/emqx/etc
      - ../.onadata_mqtt/log:/opt/emqx/log
